### ISSUE TITLE
Reduce log information

### ISSUE THREAD

**Issue by MrBretze** [tpwalke2/BlueMapSignMarkers#47]
It's possible to add an option to disable or reduce the log ?

![image](https://github.com/tpwalke2/BlueMapSignMarkers/assets/5050734/50c94511-014b-49bb-8fd7-f19f8477356d)

This is my server when is start

**Comment by tpwalke2** [comment]
I agree that a lot of these logging entries are unnecessary for the default case. I have moved some into the "debug" level since they are better suited for deeper troubleshooting. I have left a few in the "info" category to provide some basic information about how the mod is operating.

I'm going to test a pre-release build on my server. If that works correctly, I will prepare a release version.

**Comment by tpwalke2** [comment]
The latest release at https://modrinth.com/mod/bluemap-sign-markers/version/1.20.1-0.1.1.10 contains significantly reduced logging.
