### ISSUE TITLE
Multiple POI types

### ISSUE THREAD

**Issue by Sheridan** [tpwalke2/BlueMapSignMarkers#49]
Please add the ability to create different labels. I want different icons to be displayed for different types of POIs. I think the easiest way would be to give an example of the configuration as I see it:
```
{
  "marker_types":
  [
    {
      "poiPrefix": "[poi]",
      "icon": "default.png"
    },
    {
      "poiPrefix": "[gate]",
     "icon": "gate.png"
    },
    {
      "poiPrefix": "[spawner]",
      "icon": "spawner.png"
    }
  ],
}
```

**Comment by tpwalke2** [comment]
This is a good idea. Thank you!

**Comment by tpwalke2** [comment]
@Sheridan, current progress in my dev environment is that it can load the configurations and put the markers in different groups on the map. I'm now working on making sure that existing sign configurations correctly load with the new configuration format.

**Comment by Sheridan** [comment]
It might be worth doing so (pseudocode):
```
void loadOldConf() { ... }
void loadNewConf() { ... }
void loadConf()
{
  if(json.exists("marker_types"))
  {
    loadNewConf();
  }
  else
  {
    loadOldConf();
  }
}
```

**Comment by tpwalke2** [comment]
@Sheridan, I have released a new version that supports multiple POI types. The solution differs slightly from your example, but that's because I wanted to make sure I left it open for some of the features I want to add in the future. A sample configuration is available in the [readme](https://github.com/tpwalke2/BlueMapSignMarkers/blob/main/README.md).

The mod will automatically update your configuration files to the new format on the first run.

You can download the release here: https://modrinth.com/mod/bluemap-sign-markers/version/1.20.1-0.2.0.15

This is a useful feature. Thank you for sharing the idea!
